#include <Number.h>

#ifndef VEHICLE_H
#define VEHICLE_H

const char Vehicle_Name[VEHICLE_NUMBER + 1][50] = { "\0",
	"R-12 -  Salus  救护车",
	"R-12b -  Salva  消防车",
	"Dunne Dousing Engine 3r",
	"Dunne Responder 3e",
	"O Brien V.113 Gravekeeper",
	"T3  Xiphos ",
	"O Brien V.130 Wild Jack",
	"O Brien V.121 Highlander",
	"T5  Percutio ",
	"O Brien V.101 Freeman",
	"T8  Gemini ",
	"O Brien v.190 Knave",
	"O Brien V.110",
	"R-15 -  Chariot ",
	"Dunne Caravaner 2f",
	"BMS - Universal Assembly Rig",
	///////////////2 lines///////////////////
	"BMS - Fabricator",
	"BMS -2型 移动式吊车",
	"Noble Widow MK.XVII",
	"Noble Widow MK.XIV",
	"GA6  Cestus ",
	"Duncan s Coin 20mm",
	"AA-2  Battering Ram ",
	"Balfour Rampart 68mm",
	"Collins 68mm反坦克炮",
	"40-45  Smelter ",
	"Balfour Wolfhound 40mm",
	"G40  Sagittarii ",
	"Swallowtail 988/127-2",
	"Balfour Falconer 250mm",
	"BMS - Packmule 平板卡车",
	"Rooster - Lamploader",
	///////////////2 lines///////////////////
	"HH-d  Peltast ",
	"HH-a  Javelin ",
	"HH-b  Hoplite ",
	"Niska-Rycker Mk.IX Skycaller",
	"Niska Mk.II Blinder",
	"Niska Mk.III Scar Twin",
	"Niska Mk.I半履带战车",
	"BMS - Scrap Hauler",
	"AU-A150 Taurine Rigger",
	"Cnute Cliffwrest",
	"AB-8  Acheron ",
	"AB-11  Doru ",
	"Mulloy LPC",
	"945g  Stygian Bolt ",
	"Balfour Stockade 75mm",
	"120-68  Koronides 野战榴弹炮",
	///////////////2 lines///////////////////
	"Rycker 4/3-F Wasp Nest",
	"HC-2  Scorpion ",
	"Devitt-Caine Mk.IV MMR",
	"H-5  Hatchet ",
	"Devitt Ironhide Mk.IV",
	"H-19  Vulcan ",
	"H-8  Kranesca ",
	"H-10  Pelekys ",
	"Devitt Mk.III",
	"Rooster - Tumblebox",
	"86K-a  Bardiche ",
	"Gallagher Thornfall Mk.VI",
	"Gallagher Highwayman Mk.III",
	"Gallagher Outlaw Mk.II",
	"86K-c  Ranseur ",
	"Silverhand Lordscar - Mk.X",
	///////////////2 lines///////////////////
	"85K-b  Falchion ",
	"85V-g  Talos ",
	"85K-a  Spatha ",
	"Silverhand Chieftain - Mk.VI",
	"Silverhand - Mk.IV",
	"HC-7  Ballista ",
	"03MM  Caster ",
	"00MS  Stinger ",
	"Kivela Power Wheel 80-1",
	"RR-3  Stolon 油罐车",
	"Dunne Fuelrunner 2d",
	"Rooster - Junkwagon",
	"King Jester Mk.I-1",
	"King Gallant Mk.II",
	"King Spire Mk.I",
	"UV-05a Argonaut ",
	///////////////2 lines///////////////////
	"UV-24  Icarus ",
	"Drummond Spitfire 100d",
	"UV-5c  Odyssey ",
	"Drummond Loscann 55c",
	"Drummond 100a",
	"T12  Actaeon 小坦克",
	"T14  Vesta  小坦克",
	"T13  Deioneus  火箭发射车",
	"T20  Ixion  小坦克",
	"R-1 Hauler",
	"Dunne Leatherback 2a",
	"R-5  Atlas  Hauler",
	"Dunne Loadlugger 3c",
	"R-5b  Sisyphus  Hauler",
	"Dunne Landrunner 12c",
	"R-17  Retiarius  Skirmisher",
	///////////////2 lines///////////////////
	"R-9  Speartip  Escort",
	"Dunne Transport"
};


#endif // !VEHICLE_CRATE_H
