#include <Number.h>

#ifndef VEHICLE_CRATE_H
#define VEHICLE_CRATE_H

const char Vehicle_Crate_Name[VEHICLE_CRATE_NUMBER + 1][50] = { "\0",
	"R-12 - Salus 救护车",
	"Dunne Responder 3e",
	"T3  Xiphos ",
	"O Brien v.190 Knave",
	"O Brien V.110",
	"R-15 -  Chariot ",
	"Dunne Caravaner 2f",
	"Noble Widow MK.XIV",
	"AA-2  Battering Ram ",
	"Collins 68mm反坦克炮",
	"Balfour Wolfhound 40mm",
	"G40  Sagittarii ",
	"Swallowtail 988/127-2",
	"Balfour Falconer 250mm",
	"BMS - Packmule 平板卡车",
	"HH-a  Javelin ",
	"Niska Mk.I半履带战车",
	"AB-8  Acheron ",
	"Mulloy LPC",
	"120-68  Koronides 野战榴弹炮",
	"H-5  Hatchet ",
	"Devitt Mk.III",
	"86K-a  Bardiche ",
	"Gallagher Outlaw Mk.II",
	"85K-b  Falchion ",
	"Silverhand - Mk.IV",
	"HC-7 Ballista ",
	"03MM  Caster ",
	"Kivela Power Wheel 80-1",
	"RR-3  Stolon 油罐车",
	"Dunne Fuelrunner 2d",
	"装甲战斗拖拉机",
	"风暴坦克",
	"PL-1  Phalanx ",
	"轿车",
	"征用卡车",
	"Rooster - Junkwagon",
	"King Spire Mk.I",
	"UV-05a Argonaut ",
	"Drummond 100a",
	"T12  Actaeon 小坦克",
	"R-1 Hauler",
	"R-5  Atlas  Hauler",
	"Dunne Loadlugger 3c",
	"Dunne Transport",
	"BMS - Aquatipper",
	"BMS - Ironship",
	"Type C -  Charon ",
	"74b-1 Ronan Gunship",
	"BMS - Universal Assembly Rig",
	"BMS - 2型 移动式吊车"
};


#endif // !VEHICLE_CRATE_H
